#include<stdio.h>
int address(int a);
int main(){
    int a;
    printf("the address of a is %u\n",&a);
    printf("the address generated by function is %d\n",address(a));
    return 0;
}
int address(int a){
    
    int *add = &a;
    return *add;
}